### ISSUE TITLE
Standing up a local version of the Tracker Radar and the Tracker Radar Detector

### ISSUE THREAD

**Issue by billfitzgerald** [duckduckgo/tracker-radar#106]
@dharb - thank you for the [breakdown](https://github.com/duckduckgo/tracker-radar/issues/101#issuecomment-1029520226) you gave in $#101 - super helpful, and this all makes sense.

I'm moving this over to a new issue from because #101 is closed and I don't want to clutter the thread.

Two questions before I get started: 

1. Am I correct in assuming that the only value I need to worry about setting in the [config.json](https://github.com/duckduckgo/tracker-radar-detector/blob/main/config.json#L3) in the `tracker-radar-detector` is the value for "trackerDataLoc" ? I'm assuming this because I'm not looking at any of the other data sets/sources in what we're talking about here. 

2. Making 100% sure I am understanding this correctly: [privacy_policies.json](https://github.com/duckduckgo/tracker-radar/blob/main/build-data/static/privacy_policies.json) is the authoritative source of data for privacy policies used in the system? I hope I'm understanding this correctly, because that's super easy to work with. 

Thank you for your help here - the Tracker Radar is incredibly useful, and it's nice to be able to contribute back.

**Comment by billfitzgerald** [comment]
I have this sorted out, so no need for a response here.

I have a version up and running; pull requests coming either over the weekend or early next week.

I also will probably document the process - it's largely what is [included here](https://github.com/duckduckgo/tracker-radar/issues/101#issuecomment-1029520226), with a couple additional details.

**Comment by billfitzgerald** [comment]
This issue can probably be closed - I put together a writeup of getting this set up: https://www.funnymonkey.com/2022/02/working-with-duckduckgos-tracker-radar/

I think most of what I have is accurate - it was what I used to create the pull requests in the other issues, so it appears to be working.

If there is anything horribly wrong in my writeup and you have time to flag it, please let me know, and if there is anything that would be helpful in my writeup please incorporate it where it works.

**Comment by dharb** [comment]
@billfitzgerald that is a fantastic guide, leagues better than the instructions I gave you 😄. Thank you so much for doing that. Everything looks great, just one tiny nit: in the second paragraph I think you mean Tracker Radar Detector, not Tracker Radar Collector. Collector is our crawler, Detector is all the code that builds the Tracker Radar data set.
