### ISSUE TITLE
Add privacy policy for Citrix

### ISSUE THREAD

**Issue by billfitzgerald** [duckduckgo/tracker-radar#109]
Semi-related to #104 

Citrix does not currently have a privacy policy listed.

I believe that for Citrix services, this DPA would be the correct document: https://www.citrix.com/content/dam/citrix/en_us/documents/buy/data-processing-addendum-en.pdf

The [Citrix site Privacy Policy](https://www.citrix.com/about/legal/privacy/) specifies that their site policy does not apply to data processed for customers, and they point people to the DPA.

If this is the correct document, I'd be glad to update `privacy_policies.json` with this information.

**Comment by billfitzgerald** [comment]
I [added this in to the pull request}(https://github.com/duckduckgo/tracker-radar/pull/108/commits/f1ee86bf31dc0ee8f174cef30ea7b113858895a9) - it's a pretty minor addition, with the caveat that another set of eyes should determine whether or not the DPA is a better link than the web site privacy policy.

**Comment by dharb** [comment]
This makes sense to me - thanks for tracking down the DPA!
