### ISSUE TITLE
Wrong case in one key name in entity_map.json

### ISSUE THREAD

**Issue by cuihaoleo** [duckduckgo/tracker-radar#137]
Here it is:
```
$ grep displayname build-data/generated/entity_map.json
        "displayname": "Miracle SASU"
```

It should be `displayName` as in other objects.

**Comment by dharb** [comment]
Thanks for flagging @cuihaoleo, much appreciated. I'll get that fixed and will have to look into what happened there.

**Comment by dharb** [comment]
Sorry for the delay here, this is now addressed thanks to @h1t35h!
