### ISSUE TITLE
False Positive Domain/Entity on Tracking Radar

### ISSUE THREAD

**Issue by carlhancock** [duckduckgo/tracker-radar#227]
The domain name gravity.com is currently listed as part of a tracking entity that no longer exists.  See the entity here:

https://github.com/duckduckgo/tracker-radar/blob/740114a01bc2c8635cb45631659a9bf605c4a722/entities/Gravity.com%20LLC.json

We acquired the domain name gravity.com at the beginning of 2022 and are not in the business of ad, user or any kind of tracking.

The former owner was an ad tech company in the early to mid-2010's that was acquired by AOL and subsequently shut down.

You will see the gravity.com domain name currently redirects to the primary web site for our commercial OSS product.  We have plans to migrate to this domain as our primary next year and I'm working on getting it removed from any tracking lists, etc. for that reason.

Can this be removed or ideally the Gravity.com entity removed entirely or at the very least the name changed from Gravity.com LLC to Gravity LLC and the gravity.com domain removed from the domains associated with the entity? It is a company that no longer exists and that domain name is now our property.

**Comment by dharb** [comment]
Hey @carlhancock, thanks for filing this issue and for letting us know that the gravity.com domain has changed hands! Happy to get this updated for you - I'll go ahead and move gravity.com to a separate Gravity LLC entity.

**Comment by dharb** [comment]
@carlhancock on second thought, from https://www.gravityforms.com/privacy/ it looks like the owner company is Rocketgenius, Inc.? The way this entity data works is we parent companies to their domains, so I'll update this to create a new Rocketgenius, Inc. entity, which owns gravity.com, gravityforms.com, gravityapi.com, and rocketgenius.com.
