### ISSUE TITLE
Feature request: Display data in a website

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [duckduckgo/tracker-radar#27]
https://whotracks.me/trackers.html is a website where the data collected by Ghostery about trackers can be seen in a very simple and complete way. Is there any chance you guys could do something similar with your data?

**Comment by a-privacy-conscious-user** [comment]
Here you have for example the GitHub page of Whotracksme website code https://github.com/cliqz-oss/whotracks.me/tree/master/templates

**Comment by SlayterDev** [comment]
While DuckDuckGo has no official plans to build a website at this time an unofficial prototype version created as a hack days project exists here: https://slayterdev.github.io/tracker-radar-wiki/

Please note that this version is not officially supported by DuckDuckGo and may contain inaccurate data.
