### ISSUE TITLE
git clone/checkout issue on Windows

### ISSUE THREAD

**Issue by Ratcreamsoup** [duckduckgo/tracker-radar#3]
I know that I probably shouldn't use Windows in the first place, but for those of us who are stuck with this OS for some reason or other, it would make life much easier, if the file-/pathnames would be Windows filesystem friendly.

Currently I get
error: invalid path 'entities/"Agency of investigative reporters" Company limited.json'
when trying to checkout the working tree. I know I could fiddle some to omit this one path on checkout, but it'd become tedious to keep upstream in sync with the local repo then.

Is there some way that file- and pathnames could be sanitized before being added to the repo?

Thank you.

**Comment by jdorweiler** [comment]
Is it the quotes that causes the problem?

**Comment by Ratcreamsoup** [comment]
> Is it the quotes that causes the problem?

Yes, in Windows certain chars cannot be part of folder- or filenames, double quotes are among them. See https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file for reference.

**Comment by jdorweiler** [comment]
Thanks, I'll see if we can get this fixed.

**Comment by dharb** [comment]
@Ratcreamsoup thanks for pointing this out, and for the link! I'm guilty of not doing dev on windows, so it's a bit of a blindspot. I'll get this taken care of for you.
