### ISSUE TITLE
Update Ownership Information for Qualtrics in Tracker Radar

### ISSUE THREAD

**Issue by techware01** [duckduckgo/tracker-radar#303]
**Description:**
The current ownership information for Qualtrics (domain: qualtrics.com) in the DuckDuckGo Tracker Radar is outdated. According to the latest information on Wikipedia, Qualtrics is no longer owned by SAP, as all shares were sold to Silver Lake and co-investors. This change in ownership should be reflected in the Tracker Radar database to ensure accurate tracking and reporting.

**Affected File:**
- `domains/US/qualtrics.com.json`

**Reference:**
For more details, please refer to the Wikipedia page on Qualtrics: [Qualtrics - Wikipedia](https://en.wikipedia.org/wiki/Qualtrics)

**Action Required:**
Please verify the current ownership status of Qualtrics and update the `qualtrics.com.json` file in the Tracker Radar accordingly to reflect that its change of ownership.

**Thank you!**

**Comment by dharb** [comment]
Thanks for flagging @techware01! Appreciate it. Addressed in https://github.com/duckduckgo/tracker-radar/pull/304
