### ISSUE TITLE
Request for a tracker-distribution overview

### ISSUE THREAD

**Issue by shwadi** [duckduckgo/tracker-radar#7]
First off: Thank you for sharing these crawler-results

I wonder if you could add an n to m overview of the tracker to domain
relationship?  A simple csv-matrix would be sufficient for this purpose.

With such a matrix one could answer questions like:
 * Which tracker does this domain use? (easy to determine)
 * In which domains is this tracker build in? (the real purpose)

So far I couldn't find such information in the current dataset.
Or am I just missing something? If you excluded this information intentionally:
is there another publically available dataset to answer the above questions?

**Comment by jdorweiler** [comment]
We don't have a csv summary, but a list of example sites for each resource was added in the last update.
