### ISSUE TITLE
Suspicious Scripts + tracker radar

### ISSUE THREAD

**Issue by pooneh-nb** [duckduckgo/tracker-radar#87]
@jdorweiler 
How are you determining "suspicious scripts" when you compute the weight of each API here:  api_fingerprint_weights.json?

**Comment by kdzwinel** [comment]
Hey Pouneh! Great to have you here.

We collect information only about APIs that can be used for fingerprinting. If any script calls 15 or more of those APIs then we tag it as "suspicious". You can find full code that does that here:

https://github.com/duckduckgo/tracker-radar-detector/blob/b20bac5226efff0132dc13432d01b0ed5321878d/src/trackers/classes/crawl.js#L9

LMK if you have any follow up questions.

**Comment by pooneh-nb** [comment]
Hi Konrad! Happy to hear from you. 
Got it, so you have a list of "suspicious APIs" at start point. That makes sense.
